#!/bin/sh

# Определение директории, где находится xkeen
script_dir="$(cd "$(dirname "$0")" && pwd)"

# Скрываем основную директорию xkeen
install_xkeen_rename() {
    source_dir="_xkeen"
    target_dir=".xkeen"
    source_path="$script_dir/$source_dir"
    target_path="$script_dir/$target_dir"

    if [ -d "$source_path" ]; then
        if [ -d "$target_path" ]; then
            rm -rf "$target_path" 2>/dev/null
        fi
        mv "$source_path" "$target_path"
    fi
    rm /opt/root/install.sh 2>/dev/null
}
install_xkeen_rename

add_chmod_init() {
    chmod +x $initd_dir/S24xray
    chmod +x $initd_dir/S99xkeenstart
}

# Импортируем модули
. "$script_dir/.xkeen/import.sh"

# Очищаем журнал перед работой
    logs_clear
	
xkeen_info() {
    opkg update >/dev/null 2>&1
    opkg upgrade >/dev/null 2>&1
    # Проверяем установку пакетов
    info_packages
    logs_packages_info_xkeen

    # Собираем необходимую информацию о процессоре
    info_cpu
    logs_cpu_info_xkeen

    # Проверяем установку xray
    info_xray
    logs_xray_info_xkeen

    # Проверяем установленные базы geosite
    info_geosite
    logs_geosite_info_xkeen

    # Проверяем установленные базы geoip
    info_geoip
    logs_geoip_info_xkeen

    # Проверяем статус автообновления
    info_cron
    logs_cron_info_xkeen

    # Проверяем версию xkeen
    info_version_xkeen
    logs_version_xkeen_info_xkeen

    # Проверяем актуальность xkeen
    info_compare_xkeen
    logs_compare_xkeen_info_xkeen

    # Проверяем версию xray
    info_version_xray
    logs_version_xray_info_xkeen

    # Проверяем актуальность xray
    info_compare_xray
    logs_compare_xray_info_xkeen

    # Устанавливаем недостающие пакеты
    install_packages
    logs_install_packages_xkeen
}

case "$1" in

    -io)    # Установка XKeen OffLine
        clear
        echo
        echo "  Установка XKeen OffLine"

        xkeen_info
        logs_cpu_info_console
        if [ -z "$architecture" ]; then
            exit 1
        fi

        if [ -f "$install_dir/xray" ]; then
            chmod +x $install_dir/xray
        else
            clear
            echo
            echo -e "  ${red}Не найден бинарный файл xray${reset}"
            echo
            echo -e "  Поместите файл xray архитектуры ${green}$architecture${reset} в директорию /opt/sbin/ и начните установку снова"
            echo
            echo -e "  Страница загрузок xray: ${yellow}https://github.com/XTLS/Xray-core/releases/latest${reset}"
            echo
            exit 1
        fi

        install_configs
        logs_install_configs_info_xkeen

        if [ ! -d "$geo_dir" ]; then
            mkdir -p "$geo_dir"
        fi

        clear
        echo
        delete_register_xkeen
        logs_delete_register_xkeen_info_xkeen

        echo -e "  Выполняется регистрация ${yellow}XKeen${reset}"
        register_xkeen_list
        logs_register_xkeen_list_info_xkeen
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_xkeen
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_xkeen
        logs_register_xkeen_status_info_console

        delete_register_xray
        logs_delete_register_xray_info_xkeen

        echo -e "  Выполняется регистрация ${yellow}Xray${reset}"
        register_xray_list
        logs_register_xray_list_info_xkeen
        logs_register_xray_list_info_console

        register_xray_control
        logs_register_xray_control_info_xkeen
        logs_register_xray_control_info_console

        register_xray_status
        logs_register_xray_status_info_xkeen
        logs_register_xray_status_info_console

        if [ -f "$install_dir/xray" ]; then
            chmod +x $install_dir/xray
        fi

        register_xray_initd
        register_autostart

        # Создаем init для cron
        echo
        $initd_dir/S05crond stop >/dev/null 2>&1
        [ -e "$initd_dir/S05crond" ] && rm -f "$initd_dir/S05crond"

        register_cron_initd

        $initd_dir/S05crond start >/dev/null 2>&1

        # Исправление регистраций
        fixed_register_packages

        register_mihomo

        # Удаляем временные файлы
        delete_tmp
        logs_delete_tmp_info_xkeen
        sleep 2

        clear
        echo
        echo -e "  ${green}Установка XKeen выполнена!${reset}"
        echo
        echo -e "  1. Поместите необходимые dat-файлы в директорию '${yellow}$geo_dir/${reset}'"
        echo -e "  2. Настройте конфигурацию Xray по пути '${yellow}$install_conf_dir/${reset}'"
        echo -e "  3. Запустите XKeen командой ${yellow}xkeen -start${reset}"
        echo -e "  4. ${green}Enjoy!${reset}"
        echo
        echo -e "  Если хотите переключить XKeen на ядро ${yellow}mihomo${reset}"
        echo
        echo -e "  1. Поместите бинарники ${yellow}mihomo${reset} и ${yellow}yq${reset} в директорию '${yellow}$install_dir${reset}'"
        echo -e "  2. Сделайте их исполняемыми командой '${yellow}chmod +x /opt/sbin/xray /opt/sbin/yq${reset}'"
        echo -e "  3. Настройте конфигурацию в файле '${yellow}$mihomo_conf_dir/config.yaml${reset}'"
        echo -e "  4. Переключите ядро командой ${yellow}xkeen -mihomo${reset}"
        echo -e "  5. Запустите XKeen командой ${yellow}xkeen -start${reset}"
        echo -e "  6. ${green}Enjoy!${reset}"
        echo
        echo -e "  Для вывода Справки выполните ${yellow}xkeen -h${reset}"
    ;;


    -i)    # Запуск полного цикла установки
        . "$script_dir/.xkeen/import.sh"
        clear
        echo
        echo "  Запуск полного цикла установки XKeen"

        xkeen_info
        logs_cpu_info_console
        if [ -z "$architecture" ]; then
            exit 1
        fi

        # Устанавливаем xray
        echo
        download_xray
        logs_download_xray_info_xkeen

        if [ -z $bypass_xray ]; then
            install_xray
        fi

        xray_installed="installed"
        info_version_xray
        sleep 2

        clear
        # Устанавливаем geosite
        choice_geosite
        logs_choice_geosite_info_xkeen

        delete_geosite
        logs_delete_geosite_info_xkeen

        install_geosite
        logs_install_geosite_info_xkeen
        sleep 2

        clear
        # Устанавливаем geoip
        choice_geoip
        logs_choice_geoip_info_xkeen

        delete_geoip
        logs_delete_geoip_info_xkeen

        install_geoip
        logs_install_geoip_info_xkeen
        sleep 2

        clear
        # Настраиваем автоматические обновления
        info_cron
        choice_update_cron
        update_cron_geofile_task
        logs_choice_update_cron_info_xkeen
        clear
        choice_cron_time
        logs_choice_cron_time_info_xkeen

        install_cron
        logs_install_cron_info_xkeen

        clear
        echo
        install_configs
        logs_install_configs_info_xkeen

        echo
        delete_register_xkeen
        logs_delete_register_xkeen_info_xkeen

        echo -e "  Выполняется регистрация ${yellow}XKeen${reset}"
        register_xkeen_list
        logs_register_xkeen_list_info_xkeen
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_xkeen
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_xkeen
        logs_register_xkeen_status_info_console

        delete_register_xray
        logs_delete_register_xray_info_xkeen

        echo -e "  Выполняется регистрация ${yellow}Xray${reset}"
        register_xray_list
        logs_register_xray_list_info_xkeen
        logs_register_xray_list_info_console

        register_xray_control
        logs_register_xray_control_info_xkeen
        logs_register_xray_control_info_console

        register_xray_status
        logs_register_xray_status_info_xkeen
        logs_register_xray_status_info_console

        register_xray_initd
        register_autostart

        # Создаем init для cron
        echo
        $initd_dir/S05crond stop >/dev/null 2>&1
        [ -e "$initd_dir/S05crond" ] && rm -f "$initd_dir/S05crond"
        register_cron_initd
        $initd_dir/S05crond start >/dev/null 2>&1

        # Исправление регистраций
        fixed_register_packages
        sleep 2

        clear
        choice_add_mihomo
        if [ "$add_mihomo" = "true" ]; then
            echo
            download_mihomo

            if [ -z $bypass_mihomo ]; then
                install_mihomo
            fi

            mihomo_installed="installed"
            register_mihomo
        fi

        # Удаляем временные файлы
        delete_tmp
        logs_delete_tmp_info_xkeen
        rm -f "$install_dir/xray_bak" "$install_dir/mihomo_bak"
        rm -rf "$xtmp_dir" "$mtmp_dir"
        sleep 2

        clear
        echo
        echo -e "  ${green}Установка XKeen выполнена!${reset}"
        echo
        echo -e "  1. Настройте конфигурацию Xray по пути '${yellow}$install_conf_dir/${reset}'"
        echo -e "  2. Запустите XKeen командой ${yellow}xkeen -start${reset}"
        echo -e "  3. ${green}Enjoy!${reset}"
        echo
        if [ "$mihomo_installed" = "installed" ]; then
            echo -e "  Если хотите переключить XKeen на ядро ${yellow}Mihomo${reset}"
            echo
            echo -e "  1. Настройте его конфигурацию в файле '${yellow}$mihomo_conf_dir/config.yaml${reset}'"
            echo -e "  2. Переключите ядро проксирования командой ${yellow}xkeen -mihomo${reset}"
            echo -e "  3. Запустите XKeen командой ${yellow}xkeen -start${reset}"
            echo -e "  4. ${green}Enjoy!${reset}"
            echo
        fi
        echo -e "  Для вывода Справки выполните ${yellow}xkeen -h${reset}"
    ;;


    -ug)    # Запуск обновления баз GeoFile
        echo "  Обновление установленных баз GeoFile"

        info_geosite
        logs_geosite_info_xkeen

        if [ "$geo_exists_geosite_v2fly" = "installed" ]; then
            install_v2fly_geosite="true"
        fi

        if [ "$geo_exists_geosite_antifilter" = "installed" ]; then
            install_antifilter_geosite="true"
        fi

        if [ "$geo_exists_geosite_zkeen" = "installed" ]; then
            install_zkeen_geosite="true"
        fi

        install_geosite

        info_geoip
        logs_geoip_info_xkeen

        if [ "$geo_exists_geoip_v2fly" = "installed" ]; then
            install_v2fly_geoip="true"
        fi

        if [ "$geo_exists_geoip_antifilter" = "installed" ]; then
            install_antifilter_geoip="true"
        fi

        if [ "$geo_exists_geoip_zkeenip" = "installed" ]; then
            install_zkeenip_geoip="true"
        fi

        install_geoip

        if pidof "xray" >/dev/null; then
            $initd_dir/S24xray restart on >/dev/null 2>&1
        fi

        echo -e "  Обновление установленных баз GeoFile ${green}выполнено${reset}"
    ;;


    -uk)    # Запуск обновления XKeen
        echo "  Проверка обновлений XKeen"

        xkeen_info

        if [ "$xkeen_build" = "Stable" ]; then
            if [ "$info_compare_xkeen" = "update" ]; then
                clear
                echo -e "  Найдена новая версия ${yellow}XKeen${reset}"
                backup_xkeen
                download_xkeen
                install_xkeen
                . "$script_dir/.xkeen/import.sh"

                echo -e "  Выполняется отмена регистрации предыдущей версии ${yellow}XKeen${reset}"
                delete_register_xkeen
                logs_delete_register_xkeen_info_xkeen
                logs_delete_register_xkeen_info_console

                echo -e "  Выполняется регистрация новой версии ${yellow}XKeen${reset}"
                register_xkeen_list
                logs_register_xkeen_list_info_xkeen
                logs_register_xkeen_list_info_console

                register_xkeen_control
                logs_register_xkeen_control_info_xkeen
                logs_register_xkeen_control_info_console

                register_xkeen_status
                logs_register_xkeen_status_info_xkeen
                logs_register_xkeen_status_info_console

                register_cron_initd
                register_xray_initd
                register_autostart
                choice_canel_cron_select=true
                update_cron_geofile_task

                fixed_register_packages
                delete_tmp
                logs_delete_tmp_info_xkeen
                $initd_dir/S24xray restart on >/dev/null 2>&1
                echo -e "  Обновление XKeen ${green}выполнено${reset}"
                else
                echo "  Нет доступных обновлений XKeen"
            fi
        else
            echo
            echo -e "  Обновление ${yellow}тестовой версии XKeen${reset} параметром '-uk' ${red}не предусмотрено${reset}"
        fi
    ;;


    -ux)    # Обновление ядра Xray
        . "/opt/sbin/.xkeen/01_info/03_info_cpu.sh"
        status_file="/opt/lib/opkg/status"
        info_cpu
        info_xray
        info_version_xray

        clear
        echo

        download_xray
        logs_download_xray_info_xkeen

        if [ -z $bypass_xray ]; then
            install_xray
        fi

        echo -e "  Выполняется отмена регистрации предыдущей версии ${yellow}Xray${reset}"
        delete_register_xray
        logs_delete_register_xray_info_xkeen
        logs_delete_register_xray_info_console

        echo -e "  Выполняется регистрация новой версии ${yellow}Xray${reset}"
        register_xray_list
        logs_register_xray_list_info_xkeen
        logs_register_xray_list_info_console

        register_xray_control
        logs_register_xray_control_info_xkeen
        logs_register_xray_control_info_console

        register_xray_status
        logs_register_xray_status_info_xkeen
        logs_register_xray_status_info_console

        sleep 2
        $initd_dir/S24xray restart on >/dev/null 2>&1

        echo
        echo -e "  Обновление ядра Xray ${green}выполнено${reset}"

        rm -f "$install_dir/xray_bak"
        rm -rf "$xtmp_dir"
    ;;


    -um)    # Обновление или установка ядра Mihomo
        if pidof "mihomo" >/dev/null; then
            mihomo_installed=installed
        fi

        . "/opt/sbin/.xkeen/01_info/03_info_cpu.sh"
        status_file="/opt/lib/opkg/status"
        info_cpu

        clear
        echo
        download_mihomo

        if [ -z $bypass_mihomo ]; then
            install_mihomo
        fi

        if [ "$mihomo_installed" = "installed" ]; then
            $initd_dir/S24xray restart on >/dev/null 2>&1
            echo
            echo -e "  Обновление ядра ${yellow}Mihomo${reset} ${green}выполнено${reset}"
        else
            register_mihomo
            echo
            echo -e "  Установка ядра ${yellow}Mihomo${reset} ${green}выполнена${reset}"
            echo
            echo -e "  1. Настройте его конфигурацию в файле '${yellow}$mihomo_conf_dir/config.yaml${reset}'"
            echo -e "  2. Переключите ядро проксирования командой ${yellow}xkeen -mihomo${reset}"
            echo -e "  3. Запустите XKeen командой ${yellow}xkeen -start${reset}"
            echo -e "  4. ${green}Enjoy!${reset}"
        fi

        rm -f "$install_dir/mihomo_bak"
        rm -rf "$mtmp_dir"
    ;;


    -ugc)    # Создать или изменить существующюю задачу автообновления баз GeoFile
        info_cron
        clear
        echo -e "  Создание или изменение задачи автообновления баз ${yellow}GeoFile${reset}"
        choice_update_cron
        update_cron_geofile_task
        logs_choice_update_cron_info_xkeen

        choice_cron_time
        logs_choice_cron_time_info_xkeen

        install_cron
        logs_install_cron_info_xkeen

        delete_tmp
        logs_delete_tmp_info_xkeen

        echo -e "  Создание или изменение задачи автообновления баз GeoFile ${green}выполнено${reset}"
    ;;


    -ri)    # Создать файл автозапуска XKeen
        clear
        $initd_dir/S24xray stop >/dev/null 2>&1
        [ -e "$initd_dir/S24Xray" ] && rm -f "$initd_dir/S24Xray"

        echo -e "  Создание файла автозапуска ${yellow}XKeen${reset}"
        sleep 1

        register_xray_initd
        register_autostart
        logs_register_xray_initd_info_xkeen
        logs_register_xray_initd_info_console

        echo
        echo -e "  Создание файла автозапуска XKeen ${green}выполнено${reset}"
        echo -e "  Если конфигурация настроена, то можете запустить проксирование командой '${yellow}xkeen -start${reset}'"
    ;;


    -dgc)    # Удалить задачу автообновления баз GeoFile
        info_cron
        logs_cron_info_xkeen

        clear
        echo
        echo -e "  Удаление задачи автообновления баз ${yellow}GeoFile${reset}"

        delete_cron_geofile
        logs_delete_cron_geofile_info_xkeen
        logs_delete_cron_geofile_info_console

        delete_tmp
        logs_delete_tmp_info_xkeen

        echo -e "  Удаление задачи автообновления баз GeoFile ${green}выполнено${reset}"
    ;;


    -dx)    # Удалить Xray
        clear
        echo
        echo -e "  Удаление ${yellow}Xray${reset}"

        $initd_dir/S24xray stop >/dev/null 2>&1
        opkg remove xray_s

        echo
        echo -e "  Удаление ${yellow}конфигурационных файлов Xray${reset}"

        delete_configs
        logs_delete_configs_info_console
        logs_delete_configs_info_xkeen

        echo
        echo -e "  Удаление Xray ${green}выполнено${reset}"
    ;;


    -dm)    # Удалить Mihomo
        if [ -f "$install_dir/mihomo" ]; then
            clear
            echo
            echo -e "  Удаление ${yellow}Mihomo${reset}"

            rm -f "$install_dir/mihomo" "$install_dir/yq"
            rm -rf "$mihomo_conf_dir"

            echo
            echo -e "  Удаление Mihomo ${green}выполнено${reset}"
        else
            echo
            echo -e "  Mihomo ${green}не установлен${reset}"
        fi
    ;;


    -dk)    # Удалить XKeen
        clear
        echo
        echo -e "  Удаление ${yellow}XKeen${reset}"
        opkg remove xkeen
        delete_tmp

        echo
        echo -e "  Удаление XKeen ${green}выполнено${reset}"
        echo -e "  Директорию резервных копий ${yellow}/opt/backups${reset} удалите вручную"
        echo
        echo -e "  Установить ${yellow}XKeen${reset} заново можно командами:"
        echo
        echo -e "  ${green}curl -OfL https://raw.githubusercontent.com/jameszeroX/XKeen/main/install.sh${reset}"
        echo -e "  ${green}chmod +x ./install.sh${reset}"
        echo -e "  ${green}./install.sh${reset}"
    ;;


    -dgi)    # Удалить GeoIP's
        clear
        echo
        echo -e "  Удаление всех баз ${yellow}GeoIP${reset}"

        delete_geoip_key
        logs_delete_geoip_info_xkeen
        logs_delete_geoip_info_console

        echo
        echo -e "  Удаление всех баз GeoIP ${green}выполнено${reset}"
    ;;


    -dgs)    # Удалить GeoSite's
        clear
        echo
        echo -e "  Удаление всех баз ${yellow}GeoSite${reset}"

        delete_geosite_key
        logs_delete_geosite_info_xkeen
        logs_delete_geosite_info_console

        echo
        echo -e "  Удаление всех баз GeoSite ${green}выполнено${reset}"
    ;;


    -dt)    # Удалить временные файлы XKeen
        clear
        delete_tmp
        logs_delete_tmp_info_xkeen
    ;;


    -drx)    # Удалить регистрации Xray
        clear
        echo
        echo -e "  Удаление ${yellow}регистрации Xray${reset}"

        delete_register_xray
        logs_delete_register_xray_info_xkeen
        logs_delete_register_xray_info_console

        echo -e "  Удаление регистрации Xray ${green}выполнено${reset}"
    ;;


    -drk)    # Удалить регистрации XKeen
        clear
        echo
        echo -e "  Удаление ${yellow}регистрации XKeen${reset}"

        delete_register_xkeen
        logs_delete_register_xkeen_info_xkeen
        logs_delete_register_xkeen_info_console

        echo -e "  Удаление регистрации XKeen ${green}выполнено${reset}"
    ;;


    -remove)    # Полная деинсталляция XKeen и всех зависимостей
        # Удаление задачи автообновления баз GeoFile
        info_cron
        logs_cron_info_xkeen

        clear
        echo
        echo -e "  Удаление задачи автообновления баз ${yellow}GeoFile${reset}"
        delete_cron_geofile
        logs_delete_cron_geofile_info_xkeen
        logs_delete_cron_geofile_info_console

        echo
        echo -e "  Удаление задачи автообновления баз GeoFile ${green}выполнено${reset}"
        sleep 2

        # Удаление GeoIP's
        clear
        echo
        echo -e "  Удаление всех баз ${yellow}GeoIP${reset}"

        delete_geoip_key
        logs_delete_geoip_info_xkeen
        logs_delete_geoip_info_console

        echo -e "  Удаление всех баз GeoIP ${green}выполнено${reset}"
        sleep 2

        # Удаление GeoSite's
        clear
        echo
        echo -e "  Удаление всех баз ${yellow}GeoSite${reset}"

        delete_geosite_key
        logs_delete_geosite_info_xkeen
        logs_delete_geosite_info_console

        echo -e "  Удаление всех баз GeoSite ${green}выполнено${reset}"
        sleep 2

        # Удаление файлов конфигурации Xray
        clear
        echo
        echo -e "  Удаление ${yellow}конфигурационных файлов Xray${reset}"

        delete_configs
        logs_delete_configs_info_console
        logs_delete_configs_info_xkeen

        echo
        echo -e "  Удаление конфигурационных файлов Xray ${green}выполнено${reset}"
        sleep 2

        # Удаление Xray
        clear
        echo
        echo -e "  ${yellow}Удаление${reset} Xray"

        $initd_dir/S24xray stop >/dev/null 2>&1
        opkg remove xray_s

        echo
        echo -e "  Удаление Xray ${green}выполнено${reset}"
        sleep 2

        if [ -f "$install_dir/mihomo" ]; then
            # Удаление Mihomo
            clear
            echo
            echo -e "  ${yellow}Удаление${reset} Mihomo"

            rm -f "$install_dir/mihomo" "$install_dir/yq"
            rm -rf "$mihomo_conf_dir"

            echo
            echo -e "  Удаление Mihomo ${green}выполнено${reset}"
            sleep 2
           fi

        # Удаление XKeen
        clear
        echo
        echo -e "  Удаление ${yellow}XKeen${reset}"
        opkg remove xkeen
        delete_tmp

        echo
        echo -e "  Удаление XKeen ${green}выполнено${reset}"
        sleep 2

        clear
        echo
        echo -e "  Полная деинсталляция ${yellow}XKeen${reset} и всех зависимостей ${green}выполнена${reset}"
        echo -e "  Директорию резервных копий ${yellow}/opt/backups${reset} удалите вручную"
        echo
        echo -e "  Рекомендуется ${green}перезагрузить роутер${reset}"
        echo
        echo -e "  Установить ${yellow}XKeen${reset} заново можно командами:"
        echo
        echo -e "  ${green}curl -OfL https://raw.githubusercontent.com/jameszeroX/XKeen/main/install.sh${reset}"
        echo -e "  ${green}chmod +x ./install.sh${reset}"
        echo -e "  ${green}./install.sh${reset}"
    ;;


    -rrk)    # Обновить регистрацию XKeen
        clear
        echo -e "  Обновление регистрации ${yellow}XKeen${reset}"

        info_cpu
        logs_cpu_info_xkeen
        info_version_xkeen
        logs_version_xkeen_info_xkeen

        delete_register_xkeen    
        logs_delete_register_xkeen_info_xkeen
        logs_delete_register_xkeen_info_console

        register_xkeen_list
        logs_register_xkeen_list_info_xkeen
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_xkeen
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_xkeen
        logs_register_xkeen_status_info_console

        echo
        echo -e "  Обновление регистрации XKeen в системе ${green}выполнено${reset}"
    ;;


    -rrx)    # Обновить регистрацию Xray
        clear
        echo -e "  Обновление регистрации ${yellow}Xray${reset}"

        info_xray
        logs_xray_info_xkeen
        info_cpu
        logs_cpu_info_xkeen
        info_version_xray
        logs_version_xray_info_xkeen

        delete_register_xray
        logs_delete_register_xray_info_xkeen
        logs_delete_register_xray_info_console

        register_xray_list
        logs_register_xray_list_info_xkeen
        logs_register_xray_list_info_console

        register_xray_control
        logs_register_xray_control_info_xkeen
        logs_register_xray_control_info_console

        register_xray_status
        logs_register_xray_status_info_xkeen
        logs_register_xray_status_info_console

        echo
        echo -e "  Обновление регистрации Xray в системе ${green}выполнено${reset}"
    ;;


    -k)    # Переустановка XKeen
        . "/opt/sbin/.xkeen/01_info/03_info_cpu.sh"
        status_file="/opt/lib/opkg/status"
        info_cpu

        clear
        echo -e "  Переустановка ${yellow}XKeen${reset}"

        echo
        install_xkeen
        . "$script_dir/.xkeen/import.sh"
        echo -e "  Выполняется отмена регистрации предыдущей версии ${yellow}XKeen${reset}"
        delete_register_xkeen
        logs_delete_register_xkeen_info_xkeen
        logs_delete_register_xkeen_info_console

        echo -e "  Выполняется регистрация новой версии ${yellow}XKeen${reset}"
        register_xkeen_list
        logs_register_xkeen_list_info_xkeen
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_xkeen
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_xkeen
        logs_register_xkeen_status_info_console

        register_cron_initd
        register_xray_initd
        register_autostart
        choice_canel_cron_select=true
        update_cron_geofile_task

        fixed_register_packages
        delete_tmp
        logs_delete_tmp_info_xkeen
        $initd_dir/S24xray restart on >/dev/null 2>&1

        echo
        echo -e "  Переустановка XKeen ${green}выполнена${reset}"
    ;;


    -g)    # Переустановка баз GeoFile
        clear
        info_geosite
        info_geoip

        choice_geosite
        logs_choice_geosite_info_xkeen

        delete_geosite
        logs_delete_geosite_info_xkeen

        install_geosite
        logs_install_geosite_info_xkeen
        sleep 2

        clear
        choice_geoip
        logs_choice_geoip_info_xkeen

        delete_geoip
        logs_delete_geoip_info_xkeen

        install_geoip
        logs_install_geoip_info_xkeen

        clear
        echo
        echo -e "  Переустановка баз GeoFile ${green}выполнена${reset}"
    ;;


    -kb)    # Резервное копирование XKeen
        echo -e "  Создание резервной копии ${yellow}XKeen${reset}"

        info_version_xkeen
        logs_version_xkeen_info_xkeen
        backup_xkeen
    ;;


    -kbr)    # Восстановление XKeen из резервной копии
        echo -e "  Восстановление ${yellow}XKeen${reset} из резервной копии"
        restore_backup_xkeen
    ;;


    -cb)    # Резервное копирование конфигурации Xray
        echo -e "  Создание резервной копии ${yellow}конфигурации Xray${reset}"
        backup_configs_xray
    ;;


    -cbr)    # Восстановление конфигурации Xray из резервной копии
        echo -e "  Восстановление ${yellow}конфигурации Xray${reset} из резервной копии"
        restore_backup_configs_xray
    ;;


    -mb)    # Резервное копирование конфигурации Mihomo
        echo -e "  Создание резервной копии ${yellow}конфигурации Mihomo${reset}"
        backup_configs_mihomo
    ;;


    -mbr)    # Восстановление конфигурации Mihomo из резервной копии
        echo -e "  Восстановление ${yellow}конфигурации Mihomo${reset} из резервной копии"
        restore_backup_configs_mihomo
    ;;


    -tc)    # Тест соединения
        echo "  Проверка интернет-соединения"
        tests_connection
        echo -e "  Проверка интернет-соединения ${green}выполнена${reset}"
    ;;


    -tpx)    # Показать прослушиваемые порты
        echo "  Определение прослушиваемых портов"
        tests_ports_client
    ;;


    -tfk)    # Проверить файлы XKeen
        echo -e "  Проверка файлов ${yellow}XKeen${reset}"
        logs_file_check_xkeen_xkeen
        echo -e "  Проверка файлов XKeen ${green}выполнена${reset}"
    ;;


    -tfx)    # Проверить файлы Xray
        echo -e "  Проверка файлов ${yellow}Xray${reset}"
        logs_file_check_xray_xkeen
        echo -e "  Проверка файлов Xray ${green}выполнена${reset}"
    ;;


    -v)    # Показать версию XKeen
        echo "  Версия XKeen $xkeen_current_version $xkeen_build"
    ;;


    -ad)    # Можете купить кофе Skrill)
        author_donate
    ;;


    -af)    # Обратная связь
        author_feedback
    ;;


    -start)    # Запуск XKeen
        add_chmod_init
        $initd_dir/S24xray start on
        ip route flush cache
    ;;


    -stop)    # Остановка XKeen
        add_chmod_init
        $initd_dir/S24xray stop
    ;;


    -restart)    # Перезапуск XKeen
        add_chmod_init
        $initd_dir/S24xray restart on
    ;;


    -status)    # Проверка XKeen
        $initd_dir/S24xray status
    ;;


    -auto)    # Смена режима запуска XKeen
        if grep -q 'autostart="on"' $initd_dir/S99xkeenstart; then
            sed -i 's/autostart="on"/autostart="off"/' $initd_dir/S99xkeenstart
            if grep -q 'start_auto="on"' $initd_dir/S24xray; then
                sed -i 's/start_auto="on"/start_auto="off"/' $initd_dir/S24xray
            fi
            echo -e "  Автозапуск XKeen ${red}отключен${reset}"
        else
            sed -i 's/autostart="off"/autostart="on"/' $initd_dir/S99xkeenstart
            if grep -q 'start_auto="off"' $initd_dir/S24xray; then
                sed -i 's/start_auto="off"/start_auto="on"/' $initd_dir/S24xray
            fi
            echo -e "  Автозапуск XKeen ${green}включен${reset}"
        fi
        add_chmod_init
    ;;


    -fd)    # Смена режима контроля открытых файловых дескрипторов
        if grep -q 'check_fd="on"' $initd_dir/S24xray; then
            sed -i 's/check_fd="on"/check_fd="off"/' $initd_dir/S24xray
            echo -e "  Контроль файловых дескрипторов, открытых прокси-клиентом ${red}отключен${reset}. ${yellow}Перезагрузите роутер!${reset}"
        else
            sed -i 's/check_fd="off"/check_fd="on"/' $initd_dir/S24xray
            echo -e "  Контроль файловых дескрипторов, открытых прокси-клиентом ${green}включен${reset}. ${yellow}Перезагрузите роутер!${reset}"
        fi
        add_chmod_init
    ;;


    -ap)    # Добавить порт проксирования
        shift
        add_ports_donor "$1" 
        sleep 2
        add_chmod_init
    ;;


    -dp)    # Удалить порт проксирования
        shift
        dell_ports_donor "$1"
        sleep 2
        add_chmod_init
    ;;


    -cp)    # Получить список портов, на которых работает прокси-клиент
        port_donor=$(grep -m1 '^port_donor=' /opt/etc/init.d/S24xray | cut -d'=' -f2 | tr -d '"' | tr ' ' '\n' | sed 's/^/     /')
        if [ -z "$port_donor" ] || [ "$port_donor" == "     " ]
        then
            echo -e "  Прокси-клиент работает ${yellow}на всех портах${reset}"
        else
            echo -e "  Прокси-клиент работает на портах\n${green}$port_donor${reset}"
        fi
        add_chmod_init
    ;;


    -ape)    # Добавить порт-исключение проксирования
        shift
        add_ports_exclude "$1" 
        sleep 2
        add_chmod_init
    ;;


    -dpe)    # Удалить порт-исключение проксирования
        shift
        dell_ports_exclude "$1"
        sleep 2
        add_chmod_init
    ;;


    -cpe)    # Получить список портов, исключёных из проксирования
        port_exclude=$(grep -m1 '^port_exclude=' /opt/etc/init.d/S24xray | cut -d'=' -f2 | tr -d '"' | tr ' ' '\n' | sed 's/^/     /')
        if [ -z "$port_exclude" ] || [ "$port_exclude" == "     " ]
        then
            echo -e "  ${yellow}Нет портов${reset} исключенных из проксирования"
        else
            echo -e "  Из проксирования исключены порты\n${green}$port_exclude${reset}"
        fi
        add_chmod_init
    ;;


    -modules)    # Перенос необходимых модулей из прошивки в пользовательскую директорию
        migration_modules
    ;;


    -d)    # Установка задержки автозапуска в секундах
        shift
        delay_autostart "$1"
        sleep 2
        add_chmod_init
    ;;


    -diag)
        diagnostic
    ;;


    -arch)
        archive_xkeen
    ;;


    -uktest)
        xkeen_info
        clear
        backup_xkeen
        download_xkeen_test
        install_xkeen
        . "$script_dir/.xkeen/import.sh"

        echo -e "  ${yellow}Выполняется${reset} отмена регистрации предыдущей версии XKeen"
        delete_register_xkeen
        logs_delete_register_xkeen_info_xkeen
        logs_delete_register_xkeen_info_console

        echo -e "  ${yellow}Выполняется${reset} регистрация новой версии XKeen"
        register_xkeen_list
        logs_register_xkeen_list_info_xkeen
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_xkeen
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_xkeen
        logs_register_xkeen_status_info_console

        register_cron_initd
        register_xray_initd
        register_autostart
        choice_canel_cron_select=true
        update_cron_geofile_task

        fixed_register_packages
        delete_tmp
        logs_delete_tmp_info_xkeen
        $initd_dir/S24xray restart on >/dev/null 2>&1
    ;;


    -fixed)
        entware_fixed
        xkeen_info

        download_xray

        if [ -z $bypass_xray ]; then
            install_xray
        fi
        install_configs

        register_xray_list
        register_xray_control
        register_xray_status

        register_xray_initd
        register_autostart

        fixed_register_packages

        delete_tmp
    ;;


    -xray)    # Смена ядра проксирования на Xray
        command -v xray >/dev/null 2>&1 || { echo -e "  ${red}Ошибка${reset}: Ядро Xray не установлено. Выполните установку командой ${yellow}xkeen -ux${reset}"; exit 1; }
        if grep -q 'name_client="xray"' $initd_dir/S24xray; then
            echo -e " Смена ядра ${red}не выполнена${reset}. Устройство уже работает на ядре ${yellow}Xray${reset}"
        elif grep -q 'name_client="mihomo"' $initd_dir/S24xray; then
            if pidof "mihomo" >/dev/null; then
                $initd_dir/S24xray stop
            fi
            sed -i 's/name_client="mihomo"/name_client="xray"/' $initd_dir/S24xray
            add_chmod_init
            echo -e "  ${green}Выполнена${reset} смена ядра на ${yellow}Xray${reset}"
            echo -e "  Настройте конфигурацию по пути '${yellow}$install_conf_dir/${reset}'"
            echo -e "  И запустите проксирование командой ${yellow}xkeen -start${reset}"
        else
            echo -e " Произошла ${red}ошибка${reset} при смене ядра проксирования"
        fi
    ;;


    -mihomo)    # Смена ядра проксирования на Mihomo
        command -v mihomo >/dev/null 2>&1 || { echo -e "  ${red}Ошибка${reset}: Ядро Mihomo не установлено. Выполните установку командой ${yellow}xkeen -um${reset}"; exit 1; }
        command -v yq >/dev/null 2>&1 || { echo -e "  ${red}Ошибка${reset}: не установлен парсер конфигурационных файлов Mihomo - ${yellow}yq${reset}"; exit 1; }
        if grep -q 'name_client="mihomo"' $initd_dir/S24xray; then
            echo -e " Смена ядра ${red}не выполнена${reset}. Устройство уже работает на ядре ${yellow}Mihomo${reset}"
        elif [ -f "$install_dir/mihomo" ] && [ -f "$install_dir/yq" ] && grep -q 'name_client="xray"' $initd_dir/S24xray; then
            if pidof "xray" >/dev/null; then
                $initd_dir/S24xray stop
            fi
            sed -i 's/name_client="xray"/name_client="mihomo"/' $initd_dir/S24xray
            add_chmod_init
            echo -e "  ${green}Выполнена${reset} смена ядра на ${yellow}Mihomo${reset}"
            echo -e "  Настройте конфигурацию по пути '${yellow}$mihomo_conf_dir/${reset}'"
            echo -e "  И запустите проксирование командой ${yellow}xkeen -start${reset}"
        else
            echo -e " Произошла ${red}ошибка${reset} при смене ядра проксирования"
        fi
    ;;


    -h)    # Помощь
        echo
        echo -e "${light_blue}XKeen${reset} — утилита для обеспечения работы Xray и Mihomo на роутерах Keenetic"
        echo
        echo -e "	Пример использования"
        echo -e "	xkeen -ap 80,443"
        echo -e "	xkeen	${gray}	Утилита${reset}"
        echo -e "	-ap	${gray}	Выбранный Вами ключ${reset}"
        echo -e "	80,443	${gray}	Аргумент или аргументы ключа через запятую${reset}"
        echo
        echo -e "${yellow}Установка${reset}"
        echo -e "	-i	${gray}	Основной режим установки XKeen + Xray + GeoFile + Mihomo${reset}"
        echo -e "	-io	${gray}	OffLine установка XKeen${reset}"
        echo
        echo -e "${yellow}Обновление${reset}"
        echo -e "	-uk	${gray}	XKeen${reset}"
        echo -e "	-ug	${gray}	GeoFile${reset}"
        echo -e "	-ux	${gray}	Xray${reset} (повышение/понижение версии)"
        echo -e "	-um	${gray}	Mihomo${reset} (повышение/понижение версии)"
        echo
        echo -e "${yellow}Включение или изменение задачи автообновления${reset}"
        echo -e "	-ugc	${gray}	GeoFile${reset}"
        echo
        echo -e "${yellow}Регистрация в системе${reset}"
        echo -e "	-rrk	${gray}	XKeen${reset}"
        echo -e "	-rrx	${gray}	Xray${reset}"
        echo -e "	-ri	${gray}	Автозапуск XKeen средствами init.d${reset}"
        echo
        echo -e "${red}Удаление${reset} | Утилиты и компоненты"
        echo -e "	-remove	${gray}	Полная деинсталляция XKeen${reset}"
        echo -e "	-dgs	${gray}	GeoSite${reset}"
        echo -e "	-dgi	${gray}	GeoIP${reset}"
        echo -e "	-dx	${gray}	Xray${reset}"
        echo -e "	-dm	${gray}	Mihomo${reset}"
        echo -e "	-dt	${gray}	Временные файлы${reset}"
        echo -e "	-dk	${gray}	XKeen${reset}"
        echo
        echo -e "${red}Удаление${reset} | Задачи автообновления"
        echo -e "	-dgc	${gray}	GeoFile${reset}"
        echo
        echo -e "${red}Удаление${reset} | Регистрации в системе"
        echo -e "	-drk	${gray}	XKeen${reset}"
        echo -e "	-drx	${gray}	Xray${reset}"
        echo
        echo -e "${green}Порты${reset} | Через которые работает прокси-клиент"
        echo -e "	-ap	${gray}	Добавить${reset}"
        echo -e "	-dp	${gray}	Удалить${reset}"
        echo -e "	-cp	${gray}	Посмотреть${reset}"
        echo
        echo -e "${green}Порты${reset} | Исключенные из работы прокси-клиента"
        echo -e "	-ape	${gray}	Добавить${reset}"
        echo -e "	-dpe	${gray}	Удалить${reset}"
        echo -e "	-cpe	${gray}	Посмотреть${reset}"
        echo
        echo -e "${green}Переустановка${reset}"
        echo -e "	-k	${gray}	XKeen${reset}"
        echo -e "	-g	${gray}	GeoFile${reset}"
        echo
        echo -e "${green}Резервная копия XKeen${reset}"
        echo -e "	-kb	${gray}	Создание{reset}"
        echo -e "	-kbr	${gray}	Восстановление${reset}"
        echo
        echo -e "${green}Резервная копия конфигурации Xray${reset}"
        echo -e "	-cb	${gray}	Создание{reset}"
        echo -e "	-cbr	${gray}	Восстановление${reset}"
        echo
        echo -e "${green}Резервная копия конфигурации Mihomo${reset}"
        echo -e "	-mb	${gray}	Создание{reset}"
        echo -e "	-mbr	${gray}	Восстановление${reset}"
        echo
        echo -e "${light_blue}Проверки${reset}"
        echo -e "	-tpx	${gray}	Порты, шлюз и протокол прокси-клиента${reset}"
        echo -e "	-v	${gray}	Версия XKeen${reset}"
        echo
        echo -e "${light_blue}Управление прокси-клиентом${reset}"
        echo -e "	-start	${gray}	Запуск${reset}"
        echo -e "	-stop	${gray}	Остановка${reset}"
        echo -e "	-restart${gray}	Перезапуск${reset}"
        echo -e "	-status	${gray}	Статус работы${reset}"
        echo -e "	-auto	${gray}	Включить | Отключить автозапуск прокси-клиента${reset}"
        echo -e "	-d	${gray}	Установить начальное время запуска прокси-клиента с роутером${reset}"
        echo -e "	-fd	${gray}	Включить | Отключить контроль файловых дескрипторов, открытых прокси-клиентом${reset}"
        echo -e "	-diag	${gray}	Выполнить диагностику${reset}"
        echo -e "	-xray	${gray}	Переключить XKeen на ядро Xray${reset}"
        echo -e "	-mihomo	${gray}	Переключить XKeen на ядро Mihomo${reset}"
        echo
        echo -e "${light_blue}Управление модулями${reset}"
        echo -e "	-modules ${gray}	Перенос модулей для XKeen в пользовательскую директорию${reset}"
        echo
        echo -e "${light_blue}Автор${reset}"
        echo -e "	-ad	${gray}	Если Вам полезна утилита, можете купить Мне кофе${reset}"
        echo -e "	-af	${gray}	Обратная связь${reset}"
    ;;


    *)
        echo -e "     Неизвестный ключ: ${red}$1${reset}"
        echo -e "     Список доступных ключей: ${yellow}xkeen -h${reset}"
    ;;
esac
