#!/bin/sh

# Определение директории, где находится xkeen
script_dir="$(cd "$(dirname "$0")" && pwd)"

# Скрываем основную директорию xkeen
install_xkeen_rename() {
    script_dir="$script_dir"
    source_dir="_xkeen"
    target_dir=".xkeen"
    source_path="$script_dir/$source_dir"
    target_path="$script_dir/$target_dir"

    if [ -d "$source_path" ]; then
        if [ -d "$target_path" ]; then
            rm -rf "$target_path" 2>/dev/null
        fi
        mv "$source_path" "$target_path"
    fi
    rm /opt/root/install.sh 2>/dev/null
}
install_xkeen_rename

add_chmod_init() {
    chmod +x $initd_dir/S24xray
    chmod 755 $initd_dir/S24xray
    chmod +x $initd_dir/S99xkeenstart
    chmod 755 $initd_dir/S99xkeenstart
}

# Импортируем модули
. "$script_dir/.xkeen/import.sh"

# Очищаем журнал перед работой
    logs_clear
	
xkeen_info() {
    opkg update >/dev/null 2>&1
    opkg upgrade >/dev/null 2>&1
    # Проверяем установку пакетов
    info_packages
    logs_packages_info_xkeen

    # Собираем необходимую информацию о процессоре
    info_cpu
    logs_cpu_info_xkeen

    # Проверяем установку xray
    info_xray
    logs_xray_info_xkeen

    # Проверяем установленные базы geosite
    info_geosite
    logs_geosite_info_xkeen

    # Проверяем установленные базы geoip
    info_geoip
    logs_geoip_info_xkeen

    # Проверяем статус автообновления
    info_cron
    logs_cron_info_xkeen

    # Проверяем версию xkeen
    info_version_xkeen
    logs_version_xkeen_info_xkeen

    # Проверяем актуальность xkeen
    info_compare_xkeen
    logs_compare_xkeen_info_xkeen

    # Проверяем версию xray
    info_version_xray
    logs_version_xray_info_xkeen

    # Проверяем актуальность xray
    info_compare_xray
    logs_compare_xray_info_xkeen

    # Устанавливаем недостающие пакеты
    install_packages
    logs_install_packages_xkeen
}

while [ $# -gt 0 ]; do
    case "$1" in

    -io)    # Установка XKeen OffLine
        clear
        echo "  Установка XKeen OffLine"

        xkeen_info
        logs_cpu_info_console
        if [ -z "$architecture" ]; then
            exit 1
        fi

        if [ -f "$install_dir/xray" ]; then
            chmod +x $install_dir/xray
        else
            clear
            echo ""
            echo -e "  ${red}Не найден бинарный файл xray${reset}"
            echo ""
            echo -e "  Поместите файл xray архитектуры ${green}$architecture${reset} в директорию /opt/sbin/ и начните установку снова"
            echo ""
            echo -e "  Страница загрузок: ${yellow}https://github.com/XTLS/Xray-core/releases/latest${reset}"
            echo ""
            exit 1
        fi

        # Удаляем предыдущие регистрации
        delete_register_xkeen
        logs_delete_register_xkeen_info_xkeen

        delete_register_xray
        logs_delete_register_xray_info_xkeen

        install_configs
        logs_install_configs_info_xkeen

        if [ ! -d "$geo_dir" ]; then
            mkdir -p "$geo_dir"
        fi

        # Регистрируем компоненты
        if [ -f "$install_dir/xray" ]; then
            chmod +x $install_dir/xray
        fi

        register_xray_list
        logs_register_xray_list_info_xkeen

        register_xray_control
        logs_register_xray_control_info_xkeen

        register_xray_status
        logs_register_xray_status_info_xkeen

        register_xray_initd
        register_autostart

        # Регистрируем xkeen
        register_xkeen_list
        logs_register_xray_list_info_xkeen

        register_xkeen_control
        logs_register_xray_control_info_xkeen

        register_xkeen_status
        logs_register_xkeen_status_info_xkeen

        # Создаем init для cron
        echo ""
        $initd_dir/S05crond stop >/dev/null 2>&1
        [ -e "$initd_dir/S05crond" ] && rm -f "$initd_dir/S05crond"

        register_cron_initd

        $initd_dir/S05crond start >/dev/null 2>&1

        # Исправление регистраций
        fixed_register_packages

        # Удаляем временные файлы
        echo ""
        delete_tmp
        logs_delete_tmp_info_xkeen

        sleep 2
        clear
        echo ""
        echo -e "  ${green}Установка завершена!${reset}"
        echo ""
        echo -e "  1. Поместите необходимые dat-файлы в директорию '${yellow}$geo_dir/${reset}'"
        echo -e "  2. Настройте конфигурацию Xray по пути '${yellow}$install_conf_dir/${reset}'"
        echo -e "  3. Запустите XKeen командой ${yellow}xkeen -start${reset}"
        echo -e "  4. ${green}Enjoy!${reset}"
        echo ""
        echo -e "  Для вывода Справки выполните ${yellow}xkeen -h${reset}"
        echo ""
        shift
    ;;


    -i)    # Запуск полного цикла установки
        . "$script_dir/.xkeen/import.sh"
        clear
        echo "  Запуск полного цикла установки"

        xkeen_info
        logs_cpu_info_console
        if [ -z "$architecture" ]; then
            exit 1
        fi

        # Устанавливаем xray
        echo ""
        download_xray
        logs_download_xray_info_xkeen

        if [ -z $bypass_xray ]; then
            install_xray
        fi

        xray_installed="installed"
        info_version_xray

        sleep 2
        clear

        # Устанавливаем geosite
        choice_geosite
        logs_choice_geosite_info_xkeen

        delete_geosite
        logs_delete_geosite_info_xkeen

        install_geosite
        logs_install_geosite_info_xkeen
        sleep 2
        clear

        # Устанавливаем geoip
        choice_geoip
        logs_choice_geoip_info_xkeen

        delete_geoip
        logs_delete_geoip_info_xkeen

        install_geoip
        logs_install_geoip_info_xkeen
        sleep 2
        clear

        # Настраиваем автоматические обновления
        info_cron
        choice_update_cron
        update_cron_geofile_task
        logs_choice_update_cron_info_xkeen
        clear
        choice_cron_time
        logs_choice_cron_time_info_xkeen

        install_cron
        logs_install_cron_info_xkeen
        sleep 2
        clear
        echo ""

        # Удаляем предыдущие регистрации
        delete_register_xkeen
        logs_delete_register_xkeen_info_xkeen

        delete_register_xray
        logs_delete_register_xray_info_xkeen

        install_configs
        logs_install_configs_info_xkeen

        register_xray_list
        logs_register_xray_list_info_xkeen

        register_xray_control
        logs_register_xray_control_info_xkeen

        register_xray_status
        logs_register_xray_status_info_xkeen

        register_xray_initd
        register_autostart

        # Регистрируем xkeen
        register_xkeen_list
        logs_register_xray_list_info_xkeen

        register_xkeen_control
        logs_register_xray_control_info_xkeen

        register_xkeen_status
        logs_register_xkeen_status_info_xkeen

        # Создаем init для cron
        echo ""
        $initd_dir/S05crond stop >/dev/null 2>&1
        [ -e "$initd_dir/S05crond" ] && rm -f "$initd_dir/S05crond"

        register_cron_initd

        $initd_dir/S05crond start >/dev/null 2>&1

        # Исправление регистраций
        fixed_register_packages

        clear
        choice_add_mihomo
        if [ "$add_mihomo" = "true" ]; then
            echo ""
            download_mihomo
    
            if [ -z $bypass_mihomo ]; then
                install_mihomo
            fi
    
            mihomo_installed="installed"
            register_mihomo
        fi

        # Удаляем временные файлы
        echo ""
        delete_tmp
        logs_delete_tmp_info_xkeen
        rm -f "$install_dir/xray_bak" "$install_dir/mihomo_bak"
        rm -rf "$xtmp_dir" "$mtmp_dir"

        sleep 2
        clear
        echo ""
        echo -e "  ${green}Установка завершена!${reset}"
        echo ""
        echo -e "  1. Настройте конфигурацию Xray по пути '${yellow}$install_conf_dir/${reset}'"
        echo -e "  2. Запустите XKeen командой ${yellow}xkeen -start${reset}"
        echo -e "  3. ${green}Enjoy!${reset}"
        echo ""
        if [ "$mihomo_installed" = "installed" ]; then
            echo -e "  Если хотите переключить XKeen на ядро ${yellow}mihomo${reset}"
            echo -e "  1. Настройте его конфигурацию по пути '${yellow}$mihomo_conf_dir/${reset}'"
            echo -e "  2. Переключите ядро командой ${yellow}xkeen -mihomo${reset}"
            echo -e "  3. Запустите XKeen командой ${yellow}xkeen -start${reset}"
            echo -e "  4. ${green}Enjoy!${reset}"
        echo ""
        fi
        echo -e "  Для вывода Справки выполните ${yellow}xkeen -h${reset}"
        echo ""
        shift
    ;;


    -ug)    # Запуск обновления баз GeoFile
        echo "  Обновление установленных GeoFile"

        info_geosite
        logs_geosite_info_xkeen

        if [ "$geo_exists_geosite_v2fly" = "installed" ]; then
            install_v2fly_geosite="true"
        fi

        if [ "$geo_exists_geosite_antifilter" = "installed" ]; then
            install_antifilter_geosite="true"
        fi

        if [ "$geo_exists_geosite_zkeen" = "installed" ]; then
            install_zkeen_geosite="true"
        fi

        install_geosite

        info_geoip
        logs_geoip_info_xkeen

        if [ "$geo_exists_geoip_v2fly" = "installed" ]; then
            install_v2fly_geoip="true"
        fi

        if [ "$geo_exists_geoip_antifilter" = "installed" ]; then
            install_antifilter_geoip="true"
        fi

        if [ "$geo_exists_geoip_zkeenip" = "installed" ]; then
            install_zkeenip_geoip="true"
        fi

        install_geoip

        $initd_dir/S24xray restart on >/dev/null 2>&1

        echo "  Обновление установленных GeoFile завершено"
        shift
    ;;


    -uk)    # Запуск обновления XKeen
        echo "  Проверка обновлений XKeen"

        xkeen_info

        if [ "$xkeen_beta" = "false" ]; then

            if [ "$info_compare_xkeen" = "update" ]; then
                clear
                echo -e "  Найдена новая версия ${yellow}XKeen${reset}"
                backup_xkeen
                download_xkeen
                install_xkeen
                . "$script_dir/.xkeen/import.sh"
                echo -e "  ${yellow}Выполняется${reset} отмена регистрации предыдущей версии XKeen"
                delete_register_xkeen
                logs_delete_register_xkeen_info_xkeen
                logs_delete_register_xkeen_info_console
    
                sleep 1
                echo -e "  ${yellow}Выполняется${reset} регистрация новой версии XKeen"
    
                register_xkeen_list
                logs_register_xkeen_list_info_xkeen
                logs_register_xkeen_list_info_console
    
                register_xkeen_control
                logs_register_xkeen_control_info_xkeen
                logs_register_xkeen_control_info_console
    
                register_xkeen_status
                logs_register_xkeen_status_info_xkeen
                logs_register_xkeen_status_info_console
    
                register_cron_initd
                register_xray_initd
                register_autostart
                choice_canel_cron_select=true
                update_cron_geofile_task
    
                fixed_register_packages
                delete_tmp
                logs_delete_tmp_info_xkeen
                $initd_dir/S24xray restart on >/dev/null 2>&1
                echo -e "  Обновление XKeen ${green}завершено${reset}"
            else
                echo "  Нет доступных обновлений XKeen"
            fi

        else
            echo ""
            echo -e "  Обновление ${yellow}Beta-версии XKeen${reset} параметром '-uk' ${red}не предусмотрено${reset}"
        fi
        shift
    ;;


    -ux)    # Обновление ядра Xray
        . "/opt/sbin/.xkeen/01_info/03_info_cpu.sh"
        status_file="/opt/lib/opkg/status"
        info_cpu
        info_xray
        info_version_xray

        clear
        echo ""

        download_xray
        logs_download_xray_info_xkeen

        if [ -z $bypass_xray ]; then
            install_xray
        fi

        echo -e "  ${yellow}Выполняется${reset} отмена регистрации предыдущей версии Xray"

        delete_register_xray
        logs_delete_register_xray_info_xkeen
        logs_delete_register_xray_info_console

        sleep 1
        echo -e "  ${yellow}Выполняется${reset} регистрация новой версии Xray"

        register_xray_list
        logs_register_xray_list_info_xkeen
        logs_register_xray_list_info_console

        register_xray_control
        logs_register_xray_control_info_xkeen
        logs_register_xray_control_info_console

        register_xray_status
        logs_register_xray_status_info_xkeen
        logs_register_xray_status_info_console

        sleep 2
        $initd_dir/S24xray restart on >/dev/null 2>&1

        echo ""
        echo -e "  Обновление ядра Xray ${green}завершено${reset}"
        echo ""

        rm -f "$install_dir/xray_bak"
        rm -rf "$xtmp_dir"
        shift
    ;;

    -um)    # Обновление ядра Mihomo
        . "/opt/sbin/.xkeen/01_info/03_info_cpu.sh"
        status_file="/opt/lib/opkg/status"
        info_cpu

        clear
        echo ""

        download_mihomo

        if [ -z $bypass_mihomo ]; then
            install_mihomo
        fi

        echo ""
        echo -e "  Обновление ядра Mihomo ${green}завершено${reset}"
        echo -e "  Если конфигурация Mihomo настроена и XKeen переключен на его ядро, выполните команду ${yellow}xkeen -restart${reset}"
        echo ""

        rm -f "$install_dir/mihomo_bak"
        rm -rf "$mtmp_dir"
        shift
    ;;

    -ugc)    # Создать или изменить существующюю задачу автообновления GeoFile
        info_cron
        clear
        echo -e "  Создание или изменение задачи автообновления ${yellow}GeoFile${reset}"
        choice_update_cron
        update_cron_geofile_task
        logs_choice_update_cron_info_xkeen

        choice_cron_time
        logs_choice_cron_time_info_xkeen

        install_cron
        logs_install_cron_info_xkeen

        delete_tmp
        logs_delete_tmp_info_xkeen

        echo -e "  Создание или изменение задачи автообновления GeoFile ${green}завершено${reset}"
        shift
    ;;


    -rx)    # Зарегистрировать Xray
        xkeen_info
        clear
        echo -e "  Регистрация ${yellow}Xray${reset}"
        delete_register_xray
        logs_delete_register_xray_info_xkeen
        logs_delete_register_xray_info_console

        echo -e "  ${yellow}Выполняется${reset} регистрация"
        sleep 1
        echo ""
        echo -e "  ${yellow}Проверка${reset}"

        register_xray_list
        logs_register_xray_list_info_xkeen
        logs_register_xray_list_info_console

        register_xray_control
        logs_register_xray_control_info_xkeen
        logs_register_xray_control_info_console

        register_xray_status
        logs_register_xray_status_info_xkeen
        logs_register_xray_status_info_console
        fixed_register_packages

        echo ""
        echo -e "  Проверка регистрации ${green}завершена${reset}"

        echo "  Регистрация Xray в системе завершена"
        shift
    ;;


    -ri)    # Создать правило автоматического запуска Xray
        clear
        $initd_dir/S24xray stop >/dev/null 2>&1
        [ -e "$initd_dir/S24Xray" ] && rm -f "$initd_dir/S24Xray"

        echo -e "  Создание файла автоматического запуска ${yellow}Xray${reset}"
        sleep 1

        register_xray_initd
        register_autostart
        logs_register_xray_initd_info_xkeen

        echo ""
        echo -e "  ${yellow}Проверка${reset} init.d"
        logs_register_xray_initd_info_console

        echo ""
        echo -e "  Если Ваша конфигурация Xray готова, то можете запустить его '${green}xkeen -start${reset}'"

        echo "  Создание правила автоматического запуска Xray завершено"
        shift
    ;;


    -rk)    # Зарегистрировать XKeen
        xkeen_info
        clear
        echo -e "  Регистрация ${yellow}XKeen${reset}"

        delete_register_xkeen
        logs_delete_register_xkeen_info_xkeen
        logs_delete_register_xkeen_info_console

        echo -e "  ${yellow}Выполняется${reset} регистрация"
        sleep 1
        echo ""
        echo -e "  ${yellow}Проверка${reset} регистрации"

        register_xkeen_list
        logs_register_xkeen_list_info_xkeen
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_xkeen
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_xkeen
        logs_register_xkeen_status_info_console

        fixed_register_packages

        echo ""
        echo -e "  Проверка регистрации ${green}завершена${reset}"

        echo "  Регистрация XKeen в системе завершена"
        shift
    ;;

    -dgc)    # Удалить задачу автообновления GeoFile
        info_cron
        logs_cron_info_xkeen

        clear
        echo -e "  Удаление задачи автообновления ${yellow}GeoFile${reset}"
        echo ""
        echo -e "  ${yellow}Проверка${reset} удаления задач Cron для GeoFile"

        delete_cron_geofile
        logs_delete_cron_geofile_info_xkeen
        logs_delete_cron_geofile_info_console

        echo -e "  Проверка удаления задачи Cron для GeoFile ${green}завершена${reset}"
        echo ""

        delete_tmp
        logs_delete_tmp_info_xkeen

        echo "  Удаление задачи автообновления GeoFile завершено"
        shift
    ;;


    -dx)    # Удалить Xray
        echo -e "  ${yellow}Удаление${reset} Xray"

        $initd_dir/S24xray stop >/dev/null 2>&1
        opkg remove xray_s

        echo ""
        echo -e "  Удаление Xray ${green}завершено${reset}"
        sleep 2
        shift
    ;;


    -dk)    # Удалить XKeen
        clear
        echo -e "  Удаление ${yellow}XKeen${reset}"
        opkg remove xkeen
        delete_tmp

        echo ""
        echo -e "  Удаление XKeen ${green}завершено${reset}"
        echo -e "  Директорию резервных копий ${yellow}/opt/backups${reset} удалите вручную"
        echo ""
        echo -e "  Установить ${yellow}XKeen${reset} заново можно командами:"
        echo ""
        echo -e "  ${green}curl -OfL https://raw.githubusercontent.com/jameszeroX/XKeen/main/install.sh${reset}"
        echo -e "  ${green}chmod +x ./install.sh${reset}"
        echo -e "  ${green}./install.sh${reset}"
        shift
    ;;


    -dgi)    # Удалить GeoIP's
        echo -e "  Удаление всех баз ${yellow}GeoIP${reset}"

        delete_geoip_key
        logs_delete_geoip_info_xkeen
        logs_delete_geoip_info_console

        echo ""
        echo -e "  Удаление всех баз GeoIP ${green}завершено${reset}"
        shift
    ;;


    -dgs)    # Удалить GeoSite's
        echo -e "  Удаление всех баз ${yellow}GeoSite${reset}"

        delete_geosite_key
        logs_delete_geosite_info_xkeen
        logs_delete_geosite_info_console

        echo ""
        echo -e "  Удаление всех баз GeoSite ${green}завершено${reset}"
        shift
    ;;


    -dt)    # Удалить временные файлы XKeen
        delete_tmp
        logs_delete_tmp_info_xkeen
        shift
    ;;


    -dc)    # Удалить все конфиги Xray
        echo -e "  Удаление ${yellow}конфигурационных файлов Xray${reset}"

        delete_configs
        logs_delete_configs_info_console
        logs_delete_configs_info_xkeen

        echo ""
        echo -e "  Удаление всех конфигурационных файлов Xray ${green}завершено${reset}"
        shift
    ;;


    -drx)    # Удалить регистрации Xray
        clear
        echo -e "  Удаление ${yellow}регистрации Xray${reset}"
        echo ""
        sleep 1
        echo -e "  ${yellow}Проверка${reset} удаления регистрации Xray"

        delete_register_xray
        logs_delete_register_xray_info_xkeen
        logs_delete_register_xray_info_console

        echo -e "  Проверка удаления регистрации Xray ${green}выполнена${reset}"

        echo "  Удаление регистрации Xray из системы завершено"
        shift
    ;;


    -drk)    # Удалить регистрации XKeen
        clear
        echo -e "  Удаление ${yellow}регистрации XKeen${reset}"
        echo ""
        sleep 1
        echo -e "  ${yellow}Проверка${reset} удаления регистрации XKeen"

        delete_register_xkeen
        logs_delete_register_xkeen_info_xkeen
        logs_delete_register_xkeen_info_console

        echo -e "  Проверка удаления регистрации XKeen ${green}выполнена${reset}"

        echo "  Удаление регистрации XKeen из системы завершено"
        shift
    ;;


    -remove)    # Полная деинсталляция XKeen и всех зависимостей
        # Удаление задачи автообновления GeoFile
        info_cron
        logs_cron_info_xkeen

        clear
        echo -e "  Удаление задачи автообновления ${yellow}GeoFile${reset}"
        delete_cron_geofile
        logs_delete_cron_geofile_info_xkeen
        logs_delete_cron_geofile_info_console

        echo ""
        echo -e "  Удаление задачи автообновления GeoFile ${green}завершено${reset}"
        sleep 2

        # Удаление GeoIP's
        clear
        echo -e "  Удаление всех баз ${yellow}GeoIP${reset}"

        delete_geoip_key
        logs_delete_geoip_info_xkeen
        logs_delete_geoip_info_console

        echo ""
        echo -e "  Удаление всех баз GeoIP ${green}завершено${reset}"
        sleep 2

        # Удаление GeoSite's
        clear
        echo -e "  Удаление всех баз ${yellow}GeoSite${reset}"

        delete_geosite_key
        logs_delete_geosite_info_xkeen
        logs_delete_geosite_info_console

        echo ""
        echo -e "  Удаление всех баз GeoSite ${green}завершено${reset}"
        sleep 2

        # Удаление файлов конфигурации Xray
        clear
        echo -e "  Удаление ${yellow}конфигурационных файлов Xray${reset}"

        delete_configs
        logs_delete_configs_info_console
        logs_delete_configs_info_xkeen

        echo ""
        echo -e "  Удаление конфигурационных файлов Xray ${green}завершено${reset}"
        sleep 2

        # Удаление Xray
        clear
        echo -e "  ${yellow}Удаление${reset} Xray"

        $initd_dir/S24xray stop >/dev/null 2>&1
        opkg remove xray_s

        echo ""
        echo -e "  Удаление Xray ${green}завершено${reset}"
        sleep 2

        if [ -f "$install_dir/mihomo" ]; then
            # Удаление Mihomo
            clear
            echo -e "  ${yellow}Удаление${reset} Mihomo"
    
            rm -f "$install_dir/mihomo" "$install_dir/yq"
            rm -rf "$mihomo_conf_dir"
    
            echo ""
            echo -e "  Удаление Mihomo ${green}завершено${reset}"
            sleep 2
       fi

        # Удаление XKeen
        clear
        echo -e "  Удаление ${yellow}XKeen${reset}"
        opkg remove xkeen
        delete_tmp

        echo ""
        echo -e "  Удаление XKeen ${green}завершено${reset}"
        sleep 2

        clear
        echo ""
        echo -e "  Полная деинсталляция ${yellow}XKeen${reset} и всех зависимостей ${green}выполнена${reset}"
        echo -e "  Директорию резервных копий ${yellow}/opt/backups${reset} удалите вручную"
        echo ""
        echo -e "  Рекомендуется ${green}перезагрузить роутер${reset}"
        echo ""
        echo -e "  Установить ${yellow}XKeen${reset} заново можно командами:"
        echo ""
        echo -e "  ${green}curl -OfL https://raw.githubusercontent.com/jameszeroX/XKeen/main/install.sh${reset}"
        echo -e "  ${green}chmod +x ./install.sh${reset}"
        echo -e "  ${green}./install.sh${reset}"

        shift
    ;;


    -rrk)    # Обновить регистрацию XKeen
        clear
        echo -e "  Обновление регистрации ${yellow}XKeen${reset}"

        info_cpu
        logs_cpu_info_xkeen
        info_version_xkeen
        logs_version_xkeen_info_xkeen

        delete_register_xkeen        
        logs_delete_register_xkeen_info_xkeen
        logs_delete_register_xkeen_info_console

        echo -e "  ${yellow}Выполняется${reset} обновление регистрации"
        sleep 1
        echo ""
        echo -e "  ${yellow}Проверка${reset} регистрации"

        register_xkeen_list
        logs_register_xkeen_list_info_xkeen
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_xkeen
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_xkeen
        logs_register_xkeen_status_info_console

        echo ""
        echo -e "  Проверка регистрации ${green}завершена${reset}"

        echo "  Обновление регистрации XKeen в системе завершено"
        shift
    ;;


    -rrx)    # Обновить регистрацию Xray
        clear
        echo -e "  Обновление регистрации ${yellow}Xray${reset}"

        info_xray
        logs_xray_info_xkeen
        info_cpu
        logs_cpu_info_xkeen
        info_version_xray
        logs_version_xray_info_xkeen

        delete_register_xray
        logs_delete_register_xray_info_xkeen
        logs_delete_register_xray_info_console

        echo -e "  ${yellow}Выполняется${reset} обновление регистрации"
        sleep 1
        echo ""
        echo -e "  ${yellow}Проверка${reset}"

        register_xray_list
        logs_register_xray_list_info_xkeen
        logs_register_xray_list_info_console

        register_xray_control
        logs_register_xray_control_info_xkeen
        logs_register_xray_control_info_console

        register_xray_status
        logs_register_xray_status_info_xkeen
        logs_register_xray_status_info_console

        echo ""
        echo -e "  Проверка регистрации ${green}завершена${reset}"

        echo "  Обновление регистрации Xray в системе завершено"
        shift
    ;;


    -k)    # Переустановить XKeen
        . "/opt/sbin/.xkeen/01_info/03_info_cpu.sh"
        status_file="/opt/lib/opkg/status"
        info_cpu

        clear
        echo -e "  ${yellow}Переустановка${reset} XKeen"

        echo ""
        install_xkeen
        . "$script_dir/.xkeen/import.sh"
        echo -e "  ${yellow}Выполняется${reset} отмена регистрации предыдущей версии XKeen"
        delete_register_xkeen
        logs_delete_register_xkeen_info_xkeen
        logs_delete_register_xkeen_info_console

        sleep 1
        echo -e "  ${yellow}Выполняется${reset} регистрация новой версии XKeen"
        register_xkeen_list
        logs_register_xkeen_list_info_xkeen
        logs_register_xkeen_list_info_console

        register_xkeen_control
        logs_register_xkeen_control_info_xkeen
        logs_register_xkeen_control_info_console

        register_xkeen_status
        logs_register_xkeen_status_info_xkeen
        logs_register_xkeen_status_info_console

        register_cron_initd
        register_xray_initd
        register_autostart
        choice_canel_cron_select=true
        update_cron_geofile_task

        fixed_register_packages
        delete_tmp
        logs_delete_tmp_info_xkeen
        $initd_dir/S24xray restart on >/dev/null 2>&1

        echo -e "  Переустановка XKeen ${green}завершена${reset}"
        shift
    ;;


    -kb)    # Резервное копирование XKeen
        echo "  Создание резервной копии XKeen"

        info_version_xkeen
        logs_version_xkeen_info_xkeen

        backup_xkeen

        echo "  Создание резервной копии XKeen завершено"
        shift
    ;;


    -kbr)    # Восстановление резервной копировании XKeen
        echo "  Восстановление из резервной копии XKeen"

        restore_backup_xkeen

        echo "  Восстановление из резервной копии XKeen завершено"
        shift
    ;;


    -tc)    # Тест соединения
        echo -e "  ${yellow}Проверка${reset} интернет-соединения"
        tests_connection
        echo -e "  Проверка интернет-соединения ${green}завершена${reset}"

        shift
    ;;


    -tpx)    # Показать прослушиваемые порты
        echo -e "  ${yellow}Определение${reset} прослушиваемых портов"
        tests_ports_client
    ;;


    -tfk)    # Проверить файлы XKeen
        echo -e "  ${yellow}Проверка${reset} файлов XKeen"
        logs_file_check_xkeen_xkeen
        echo -e "  Проверка файлов XKeen ${green}завершена${reset}"
        break
    ;;


    -tfx)    # Проверить файлы Xray
        echo -e "  ${yellow}Проверка${reset} файлов Xray"
        logs_file_check_xray_xkeen
        echo -e "  Проверка файлов Xray ${green}завершена${reset}"
        break
    ;;


    -v)    # Показать текущую версию
        info_version_xray
        logs_version_xray_info_xkeen
        echo "  Текущая версия XKeen $xkeen_current_version"
        break
    ;;


    -ad)    # Можете купить Мне кофе
        author_donate
        shift
    ;;


    -af)    # Обратная связь
        author_feedback
        shift
    ;;


    -start)    # Запуск Xray
        add_chmod_init
        $initd_dir/S24xray start on
        ip route flush cache
        exit 0

        shift
    ;;


    -stop)    # Остановка Xray
        add_chmod_init
        $initd_dir/S24xray stop
        exit 0

        shift
    ;;


    -restart)    # Перезапуск Xray
        add_chmod_init
        $initd_dir/S24xray restart on
        exit 0

        shift
    ;;


    -status)    # Проверка Xray

        $initd_dir/S24xray status

        shift
    ;;


    -auto)    # Переключение значения autostart между "on" и "off"
        if grep -q 'autostart="on"' $initd_dir/S99xkeenstart; then
            sed -i 's/autostart="on"/autostart="off"/' $initd_dir/S99xkeenstart
            echo -e "  Автозапуск XKeen ${red}отключен${reset}"
        else
            sed -i 's/autostart="off"/autostart="on"/' $initd_dir/S99xkeenstart
            echo -e "  Автозапуск XKeen ${green}включен${reset}"
        fi

        add_chmod_init
        exit 0
        shift
    ;;


    -fd)    # Переключение значения check_fd между "on" и "off"
        if grep -q 'check_fd="on"' $initd_dir/S24xray; then
            sed -i 's/check_fd="on"/check_fd="off"/' $initd_dir/S24xray
            echo -e "  Контроль открытых файловых дескрипторов для xray ${red}отключен${reset}. ${yellow}Перезагрузите роутер!${reset}"
        else
            sed -i 's/check_fd="off"/check_fd="on"/' $initd_dir/S24xray
            echo -e "  Контроль открытых файловых дескрипторов для xray ${green}включен${reset}. ${yellow}Перезагрузите роутер!${reset}"
        fi
        exit 0
        add_chmod_init

        shift
    ;;


    -ap)    # Добавить порт Xray
        shift
        add_ports_donor "$1" 
        sleep 2
        add_chmod_init

        shift
    ;;


    -dp)    # Удалить порт Xray
        shift
        dell_ports_donor "$1"
        sleep 2
        add_chmod_init

        shift
    ;;


    -cp)    # Получить список портов, на которых работает прокси
        port_donor=$(grep -m1 '^port_donor=' /opt/etc/init.d/S24xray | cut -d'=' -f2 | tr -d '"' | tr ' ' '\n' | sed 's/^/     /')
        if [ -z "$port_donor" ] || [ "$port_donor" == "     " ]
        then
            echo -e "  Xray работает ${yellow}на всех${reset} портах"
        else
            echo -e "  Xray ${green}работает${reset} на портах\n$port_donor"
        fi
        add_chmod_init

        shift
    ;;


    -ape)    # Добавить порт-исключение Xray
        shift
        add_ports_exclude "$1" 
        sleep 2
        add_chmod_init
        shift
    ;;


    -dpe)    # Удалить порт-исключение Xray
        shift        
        dell_ports_exclude "$1"
        sleep 2
        add_chmod_init

        shift
    ;;


    -cpe)    # Получить список портов-исключение, на которых не работает прокси
        port_exclude=$(grep -m1 '^port_exclude=' /opt/etc/init.d/S24xray | cut -d'=' -f2 | tr -d '"' | tr ' ' '\n' | sed 's/^/     /')
        if [ -z "$port_exclude" ] || [ "$port_exclude" == "     " ]
        then
            echo -e "  ${yellow}Нет портов${reset} Xray для исключения"
        else
            echo -e "  Xray ${red} не работает${reset} на портах\n$port_exclude"
        fi
        add_chmod_init

        shift
    ;;


    -modules)    # Переносит модули из прошивки в пользовательскую директорию
        migration_modules

        shift
    ;;


    -d)    # Установить задержку автозапуска в секундах
        shift
        delay_autostart "$1"
        sleep 2
        add_chmod_init

        shift
    ;;


    -diag)
        diagnostic

        shift
    ;;


    -arch)
        archive_xkeen

        shift
    ;;


    -test)

        shift
    ;;


    -fixed)
        entware_fixed
        xkeen_info

        download_xray

        if [ -z $bypass_xray ]; then
            install_xray
        fi
        install_configs

        register_xray_list
        register_xray_control
        register_xray_status

        register_xray_initd
        register_autostart

        fixed_register_packages

        delete_tmp

        shift
    ;;


    -xray)    # Смена ядра проксирования на Xray
        if grep -q 'name_client="xray"' $initd_dir/S24xray; then
            echo -e " Смена ядра ${red}не выполнена${reset}. Устройство уже работает на ядре ${yellow}Xray${reset}"
        elif grep -q 'name_client="mihomo"' $initd_dir/S24xray; then
            if pidof "mihomo" >/dev/null; then
                $initd_dir/S24xray stop
            fi
            sed -i 's/name_client="mihomo"/name_client="xray"/' $initd_dir/S24xray
            add_chmod_init
            echo -e "  ${green}Выполнена${reset} смена ядра на ${yellow}xray${reset}"
            echo -e "  Настройте конфигурацию по пути '${yellow}$install_conf_dir/${reset}'"
            echo -e "  И запустите проксирование командой ${yellow}xkeen -start${reset}"
            exit 0
        else
            echo -e " Произошла ${red}ошибка${reset} при смене ядра"
        fi

        shift
    ;;


    -mihomo)    # Смена ядра проксирования на Mihomo
        if grep -q 'name_client="mihomo"' $initd_dir/S24xray; then
            echo -e " Смена ядра ${red}не выполнена${reset}. Устройство уже работает на ядре ${yellow}Mihomo${reset}"
        elif [ -f "$install_dir/mihomo" ] && [ -f "$install_dir/yq" ] && grep -q 'name_client="xray"' $initd_dir/S24xray; then
            if pidof "xray" >/dev/null; then
                $initd_dir/S24xray stop
            fi
            sed -i 's/name_client="xray"/name_client="mihomo"/' $initd_dir/S24xray
            add_chmod_init
            echo -e "  ${green}Выполнена${reset} смена ядра на ${yellow}Mihomo${reset}"
            echo -e "  Настройте конфигурацию по пути '${yellow}$mihomo_conf_dir/${reset}'"
            echo -e "  И запустите проксирование командой ${yellow}xkeen -start${reset}"
            exit 0
        else
            echo -e " Произошла ${red}ошибка${reset} при смене ядра или ядро ${yellow}Mihomo${reset} не установлено"
        fi

        shift
    ;;


    -h)    # Помощь
        echo
        echo -e "${light_blue}XKeen${reset} — утилита для обеспечения работы Xray на роутерах Keenetic"
        echo 
        echo -e "	Пример использования"
        echo -e "	xkeen -ap 80,443"
        echo -e "	xkeen	${gray}	Утилита${reset}"
        echo -e "	-ap	${gray}	Выбранный Вами ключ${reset}"
        echo -e "	80,443	${gray}	Аргумент или аргументы ключа через запятую${reset}"
        echo
        echo -e "${yellow}Установка${reset}"
        echo -e "	-i	${gray}	Основной режим установки XKeen + Xray + GeoFile${reset}"
        echo -e "	-io	${gray}	OffLine установка XKeen${reset}"
        echo
        echo -e "${yellow}Обновление${reset}"
        echo -e "	-ug	${gray}	GeoFile${reset}"
        echo -e "	-uk	${gray}	XKeen${reset}"
        echo -e "	-ux	${gray}	Xray${reset} (повышение/понижение версии)"
        echo -e "	-um	${gray}	Mihomo${reset} (повышение/понижение версии)"
        echo 
        echo -e "${yellow}Включение или изменение задачи автообновления${reset}"
        echo -e "	-ugc	${gray}	GeoFile${reset}"
        echo 
        echo -e "${yellow}Регистрация${reset}"
        echo -e "	-rk	${gray}	XKeen${reset}"
        echo -e "	-rx	${gray}	Xray${reset}"
        echo -e "	-ri	${gray}	Автоматический запуск XKeen средствами init.d${reset}"
        echo
        echo -e "${red}Удаление${reset} | Утилиты и компоненты"
        echo -e "	-remove	${gray}	Полная деинсталляция XKeen${reset}"
        echo -e "	-dgs	${gray}	GeoSite${reset}"
        echo -e "	-dgi	${gray}	GeoIP${reset}"
        echo -e "	-dс	${gray}	Конфигурации Xray${reset}"
        echo -e "	-dx	${gray}	Xray${reset}"
        echo -e "	-dt	${gray}	Временные файлы${reset}"
        echo -e "	-dk	${gray}	XKeen${reset}"
        echo 
        echo -e "${red}Удаление${reset} | Задачи автообновления"
        echo -e "	-dgc	${gray}	GeoFile${reset}"
        echo
        echo -e "${red}Удаление${reset} | Регистрации"
        echo -e "	-drk	${gray}	XKeen${reset}"
        echo -e "	-drx	${gray}	Xray${reset}"
        echo
        echo -e "${green}Порты${reset} | Через которые будет работать клиент"
        echo -e "	-ap	${gray}	Добавить${reset}"
        echo -e "	-dp	${gray}	Удалить${reset}"
        echo -e "	-cp	${gray}	Список${reset}"
        echo
        echo -e "${green}Порты${reset} | Которые требуется исключить из работы клиента"
        echo -e "	-ape	${gray}	Добавить${reset}"
        echo -e "	-dpe	${gray}	Удалить${reset}"
        echo -e "	-cpe	${gray}	Список${reset}"
        echo
        echo -e "${green}Обновление регистрации утилит${reset}"
        echo -e "	-rrk	${gray}	XKeen${reset}"
        echo -e "	-rrx	${gray}	Xray${reset}"
        echo
        echo -e "${green}Переустановка${reset}"
        echo -e "	-k	${gray}	XKeen${reset}"
        echo
        echo -e "${green}Резервные копии${reset} | Создание"
        echo -e "	-kb	${gray}	XKeen${reset}"
        echo
        echo -e "${green}Резервные копии${reset} | Восстановление последней${reset}"
        echo -e "	-kbr	${gray}	XKeen${reset}"
        echo
        echo -e "${light_blue}Проверки${reset}"
        echo -e "	-tpx	${gray}	Порты, шлюз и протокол прокси-клиента${reset}"
        echo -e "	-v	${gray}	Версия XKeen${reset}"
        echo
        echo -e "${light_blue}Управление прокси-клиентом${reset}"
        echo -e "	-start	${gray}	Запуск${reset}"
        echo -e "	-stop	${gray}	Остановка${reset}"
        echo -e "	-restart${gray}	Перезапуск${reset}"
        echo -e "	-status	${gray}	Статус работы${reset}"
        echo -e "	-auto	${gray}	Включить  ${gray}|  Отключить запуск прокси-клиента с роутером${reset}"
        echo -e "	-d	${gray}	Установить начальное время запуска прокси-клиента с роутером${reset}"
        echo -e "	-fd	${gray}	Включить  ${gray}|  Отключить контроль открытых файловых дескрипторов для процесса xray${reset}"
        echo -e "	-diag	${gray}	Выполнить диагностику${reset}"
        echo -e "	-xray	${gray}	Переключить XKeen на ядро Xray${reset}"
        echo -e "	-mihomo	${gray}	Переключить XKeen на ядро Mihomo${reset}"
        echo
        echo -e "${light_blue}Управление модулями${reset}"
        echo -e "	-modules ${gray}	Перенос модулей для XKeen в пользовательскую директорию${reset}"
        echo
        echo -e "${light_blue}Автор${reset}"
        echo -e "	-ad	${gray}	Если Вам полезна утилита, можете купить Мне кофе${reset}"
        echo -e "	-af	${gray}	Обратная связь${reset}"
        echo
        shift
    ;;

    *)
        echo -e "     Неизвестный ключ: ${red}$1${reset}"
        echo -e "     Список доступных ключей: ${yellow}xkeen -h${reset}"
        shift
    ;;

    esac
done
