name: Create Test build to `main/test/` folder

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
  workflow_dispatch:

jobs:
  build-and-push-to-main-test-folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_config_global: true

      - name: Prepare scripts with build timestamp
        run: |
          export TZ="Europe/Moscow"
          BUILD_TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S MSK")
          mkdir -p scripts_for_build
          cp -r scripts/* scripts_for_build/

          sed -i "s/^build_timestamp=\".*\"/build_timestamp=\"$BUILD_TIMESTAMP\"/" \
            scripts_for_build/_xkeen/01_info/01_info_variable.sh

      - name: Create tar.gz archive
        run: |
          mkdir -p output
          cd scripts_for_build
          chmod +x xkeen
          find . -type f -o -type l | sed 's|^\./||' | tar -czf "../output/xkeen.tar.gz" -T -

      - name: Move archive to test folder in main
        run: |
          mkdir -p test
          mv output/xkeen.tar.gz test/

      - name: Clean up temporary files
        run: |
          rm -rf scripts_for_build output

      - name: Commit and push signed archive to test folder
        run: |
          git add test/xkeen.tar.gz
          git commit -S -m "[github-actions] automated compiling build"
          git push origin main